export const AFFIRMATION_LIST = [
  "Today, I am brimming with energy and overflowing with joy.",
  "I am superior to negative thoughts and low actions.",
  "I possess the qualities needed to be extremely successful.",
  "I am courageous and I stand up for myself.",
  "My thoughts are filled with positivity and my life is plentiful with prosperity.",
  "I acknowledge my own self-worth; my confidence is soaring.",
  "Everything that is happening now is happening for my ultimate good.",
  "I radiate beauty, charm, and grace.",
  "I am at peace with all that has happened, is happening, and will happen.",
  "My life is just beginning.",
  "My actions create constant prosperity.",
  "I am full of positive loving energy.",
  "I deserve love and I get it in abundance.",
  "I am in the process of becoming the best version of myself.",
  "My possibilities are endless.",
  "I am worthy of my dreams.",
  "I am enough.",
  "I deserve to be healthy and feel good.",
  "I am full of energy and vitality and my mind is calm and peaceful.",
  "I am grateful to be alive. It is my joy and pleasure to live another wonderful day.",
  "Good things are happening.",
  "I choose to be kind to myself and love myself unconditionally.",
  "I have the freedom & power to create the life I desire.",
  "I believe I can be all that I want to be.",
  "I give out love and it is returned to me multiplied manyfold.",
  "I am open and receptive to all the wealth life offers me.",
  "I constantly attract opportunities that create more money.",
  "Every day I am getting healthier and stronger.",
  "I honour my body by trusting the signals that it sends me.",
  "Being happy comes easy to me. Happiness is my second nature.",
];
